/**
 * GENERATED by scripts/sync-market-snapshot.ts. Do not edit.
 *
 * Source: ../punprofile-career-coaching/punprofile-work/work-pipeline/job-log.json
 *
 * Re-run the sync and commit both files when the figures should move. Nothing
 * updates this automatically, on purpose: a candidate-facing number changes
 * when someone decides it should.
 */

import type { MarketSnapshot } from "../../../scripts/sync-market-snapshot";

export const MARKET: MarketSnapshot = {
  "screened": 266,
  "published": 94,
  "employers": 45,
  "from": "07/07/2026",
  "to": "17/08/2026"
} as const;
