/**
 * GENERATED by scripts/sync-termbase.ts. Do not edit.
 *
 * Source: ../punprofile-career-coaching/punprofile-context/ctxt-content/termbase.yml
 * Source updated: 18/08/2026
 *
 * Edit the YAML in the coaching repo, re-run the sync, commit both files.
 */

import type { Termbase } from "../../../scripts/sync-termbase";

export const TERMBASE: Termbase = {
  "version": 1,
  "updated": "18/08/2026",
  "terms": [
    {
      "id": "brand-name",
      "en": "PunProfile",
      "th": [
        "PunProfile",
        "ปั้นโปรไฟล์ (PunProfile)",
        "ปั้นโปรไฟล์"
      ],
      "banned": [],
      "surfaces": [
        "all"
      ],
      "fixed": false,
      "rule": "LR-01",
      "decided": "15/08/2026",
      "why": "The wordmark is a fixed asset and is never translated. What changed on 15/08/2026 is that the Thai form is not a translation, it is the joke the name is built on: PunProfile is a play on ปั้นโปรไฟล์, to shape or mould a profile. A Thai reader who only ever sees the Latin never gets it.\n**Where the brand opens a Thai paragraph, lead with the Thai.** The pattern is Paul's own, from the pinned post: ปั้นโปรไฟล์ (PunProfile) on first mention, then ปั้นโปรไฟล์ alone afterwards. Thai first, Latin glossing it, not the other way round.\nMid-sentence mentions stay Latin. Repeating the gloss every time turns a pun into a tic.\nThree things stay Latin whatever position they sit in: the wordmark in navigation and the logo, the legal entity PunProfile Career Coaching in the privacy notice and anywhere else it names the controller, and the copyright line. A company name in a legal notice is an identifier rather than a brand voice.\n`fixed` is false because there are now three correct renderings and which one is right depends on position. The lint cannot judge that; it is a judgement the writer makes and `Language_System.md` LR-01 records.\n"
    },
    {
      "id": "product-eu-fit-check",
      "en": "EU Fit Check",
      "th": [
        "EU Fit Check"
      ],
      "banned": [],
      "surfaces": [
        "all"
      ],
      "fixed": true,
      "rule": "LR-01",
      "decided": "04/08/2026",
      "why": "The assessment feature's name, not translated. The public name is not settled."
    },
    {
      "id": "coaching-1-1",
      "en": "Coaching 1:1",
      "th": [
        "Coaching 1:1"
      ],
      "banned": [
        "โค้ชชิ่งตัวต่อตัว"
      ],
      "surfaces": [
        "app"
      ],
      "fixed": true,
      "rule": "LR-01",
      "decided": "14/08/2026",
      "why": "Paul's call. Already how this is said in Thai professional contexts, and โค้ชชิ่งตัวต่อตัว is the longest item in a menu whose other entries are two words.\n"
    },
    {
      "id": "channel-line",
      "en": "LINE",
      "th": [
        "Line"
      ],
      "banned": [
        "ไลน์",
        "LINE"
      ],
      "surfaces": [
        "all"
      ],
      "fixed": true,
      "rule": "LR-01",
      "decided": "15/08/2026",
      "why": "A brand name, in Latin script rather than transliterated. Paul's call, 15/08/2026, after the lint found consent.statement writing the transliteration while every other string wrote it in Latin. It is the PDPA string naming the channel consented to, which is the last place two spellings of one channel belong.\nTitle case, revised the same day. The company styles itself LINE in caps and Paul decided PunProfile writes Line, which is the form that sits in a Thai sentence without shouting. Both the transliteration and the all-caps form are banned, so the one remaining form is the one that ships.\nThis is about the chat application, which is a different word from ออนไลน์. A term check must not match inside it.\n"
    },
    {
      "id": "field-line-id",
      "en": "LINE ID",
      "th": [
        "Line ID"
      ],
      "banned": [],
      "surfaces": [
        "app"
      ],
      "fixed": true,
      "rule": "LR-01",
      "decided": "15/08/2026",
      "why": "The field label. Same reasoning as `channel-line`, and it is the label users see in LINE itself."
    },
    {
      "id": "official-website",
      "en": "official website",
      "th": [
        "เว็บไซต์ Official",
        "เว็บไซต์ออฟฟิชียล"
      ],
      "banned": [
        "ลิงก์ทางการ",
        "เว็บไซต์ทางการ"
      ],
      "surfaces": [
        "post"
      ],
      "fixed": false,
      "rule": "LR-05",
      "decided": "11/07/2026",
      "why": "ทางการ is formal-register and reads stiffer than a social audience expects. ลิงก์ทางการ is the original literal-translation error the rule was written from.\n**`surfaces` stays `[post]`, confirmed 18/08/2026 (Paul), and this is now a decision rather than an untested default.** The blog's first article writes เว็บไซต์ทางการ in its 30-day plan and keeps it. The register argument above is about a feed: a reader scrolling past a job post meets ทางการ as stiffness, where a reader who opened a 3,000-word guide about visa routes meets it as precision, and an official government site is exactly the thing the word is for. So the ban is post-scoped on purpose and long-form may use it.\nThe entry was checked against a blog page because nothing had ever tested it outside a post. That is the failure mode LR-08 was written after, where a wording nobody re-examined on a new surface simply persisted.\n"
    },
    {
      "id": "job-opening",
      "en": "this specific job opening",
      "th": [
        "ตำแหน่ง"
      ],
      "banned": [],
      "surfaces": [
        "post",
        "app"
      ],
      "fixed": false,
      "rule": "LR-05",
      "decided": "11/07/2026",
      "why": "โอกาส reads vaguer and more marketing-flavoured than a job-board audience expects when it points at one listing. It stays correct in the abstract or plural, ติดตามเพจเพื่อไม่พลาดโอกาสใหม่, so it is not banned outright and the lint cannot judge which sense is meant. The judge pass carries this one.\n"
    },
    {
      "id": "survey",
      "en": "survey, quiz",
      "th": [
        "survey"
      ],
      "banned": [
        "แบบเช็ก",
        "แบบเช็ค"
      ],
      "surfaces": [
        "post",
        "app",
        "message"
      ],
      "fixed": false,
      "rule": "LR-05",
      "decided": "11/07/2026",
      "why": "แบบเช็ก is an invented compound and not a real Thai term. Use the loanword rather than constructing one. Caught in Paul's edit of the pinned post.\n"
    },
    {
      "id": "relocation-package",
      "en": "relocation package, relocation budget, relocation bonus",
      "th": [
        "บัดเจ็ท Relocation",
        "Relocation budget",
        "Relocation bonus",
        "Relocation assistance"
      ],
      "banned": [
        "โบนัสช่วยย้ายถิ่นฐาน"
      ],
      "surfaces": [
        "post"
      ],
      "fixed": false,
      "rule": "LR-05",
      "decided": "04/08/2026",
      "why": "Same error as แบบเช็ก, applied to a job benefit. The concept already circulates as a loanword in Thai job-market social media.\n"
    },
    {
      "id": "visa-sponsorship",
      "en": "visa sponsorship, to sponsor a visa",
      "th": [
        "สปอนเซอร์วีซ่า"
      ],
      "banned": [
        "สนับสนุนวีซ่า"
      ],
      "surfaces": [
        "all"
      ],
      "fixed": false,
      "rule": "LR-05",
      "decided": "17/08/2026",
      "why": "Paul's decision, on the home page review. Three renderings were live at once and nothing could catch it because this entry did not exist: the pinned post carries วีซ่าสปอนเซอร์, the result screen carries ผ่านเกณฑ์สปอนเซอร์วีซ่า, and สนับสนุนวีซ่า had been drafted for the home page on the evidence of นโยบายสนับสนุนการย้ายประเทศ elsewhere in his writing. He used สปอนเซอร์วีซ่า three times in one review pass, twice as a verb. Not `fixed`, because the word order changes with the grammar around it: บริษัทสปอนเซอร์วีซ่า as a verb, การสปอนเซอร์วีซ่า as a noun, and both are his. The loanword rather than a Thai compound is LR-05's general principle, and it is the vocabulary these candidates meet in the job adverts themselves.\n"
    },
    {
      "id": "free-consultation",
      "en": "free consultation",
      "th": [
        "ปรึกษาฟรี",
        "คำปรึกษาฟรี"
      ],
      "banned": [
        "คุยฟรี",
        "แชทฟรี",
        "ทักฟรี",
        "นัดคุยฟรี"
      ],
      "surfaces": [
        "all"
      ],
      "fixed": false,
      "rule": "LR-04",
      "decided": "09/08/2026",
      "why": "ฟรี only collocates with a word that already denotes a valuable service. คุย and แชท are casual talk, which nobody expects to pay for, so ฟรี attached to them is assembled rather than spoken. Keep the casual invitation verb separate from the ฟรี value phrase.\nWidened 17/08/2026, in the other direction. The lint's stem whitelist had stopped where this error did, and failed อ่านฟรี and เปิดฟรี, both of which Paul writes and both of which pass the rule's own test: reading something, and a group being open to you, are things you might have paid for. อ่าน and เปิด are now in FREE_STEMS in `lint-thai.ts`. The four banned forms above are unchanged, which is the whole point of listing them separately.\n"
    },
    {
      "id": "posting-states",
      "en": "the posting states X",
      "th": [
        "ประกาศระบุ",
        "ประกาศเขียนไว้ว่า"
      ],
      "banned": [
        "ประกาศพูด",
        "ประกาศบอก"
      ],
      "surfaces": [
        "post"
      ],
      "fixed": false,
      "rule": "LR-06",
      "decided": "04/08/2026",
      "why": "Thai does not extend a speech act to a written document. A company as the actor, บริษัทระบุว่า, is fine. Note LR-07 caps ประกาศ at one per post regardless of which verb follows it.\n"
    },
    {
      "id": "work-rights-label",
      "en": "For those who already hold documents granting the right to work in Europe",
      "th": [
        "🛂 สำหรับผู้ที่มีเอกสารสิทธิ์ทำงานในยุโรปแล้ว"
      ],
      "banned": [
        "สำหรับผู้ที่มีสิทธิ์ทำงาน"
      ],
      "surfaces": [
        "post"
      ],
      "fixed": true,
      "rule": "LR-08",
      "decided": "14/08/2026",
      "why": "Paul's correction from the drafted สำหรับผู้ที่มีสิทธิ์ทำงาน. เอกสารสิทธิ์ points at paperwork a reader either holds or does not, checkable in a second. สิทธิ์ alone reads as an abstract entitlement and invites them to wonder whether they qualify. It carries eligibility, so it is never paraphrased. Placement is in 03_Content_System.md, Work Rights Label.\n"
    },
    {
      "id": "cta-start-assessment",
      "en": "Start the assessment",
      "th": [
        "เริ่มทำ EU Fit Check"
      ],
      "banned": [
        "เช็กความพร้อมของคุณ",
        "เช็กว่าคุณพร้อมแค่ไหน"
      ],
      "surfaces": [
        "app"
      ],
      "fixed": true,
      "rule": "LR-08",
      "decided": "15/08/2026",
      "why": "The landing page's one action. Three wordings existed until 15/08/2026: this one in cta.ts, เช็กความพร้อมของคุณ in 03_Content_System.md, and เช็กว่าคุณพร้อมแค่ไหน in a dead copy.ts key. Paul kept this one and judged the other two stiff and below standard, so both are banned rather than merely dropped. A retired wording that is only deleted comes back the next time someone writes the button from the English.\n"
    },
    {
      "id": "cta-book-consultation",
      "en": "Book a consultation",
      "th": [
        "นัดปรึกษาฟรี 30 นาที"
      ],
      "banned": [
        "นัดคุยฟรี 30 นาที"
      ],
      "surfaces": [
        "app"
      ],
      "fixed": true,
      "rule": "LR-08",
      "decided": "09/08/2026",
      "why": "The result page's action, and the compressed in-product form of the Free Consultation Hook. Not yet wired: the result page's live primary is the services page until Phase 2 captures contact details, which 03_Content_System.md App CTAs explains. Not a conflict, a deferral.\n"
    },
    {
      "id": "footer-legal",
      "en": "PunProfile Career Coaching | 2026 | All Rights Reserved",
      "th": [
        "PunProfile Career Coaching | 2026 | All Rights Reserved"
      ],
      "banned": [],
      "surfaces": [
        "app"
      ],
      "fixed": true,
      "rule": "LR-01",
      "decided": "09/08/2026",
      "why": "A Thai transliteration of a legal formula reads as a mistake, not a courtesy."
    },
    {
      "id": "nav-menu",
      "en": "Menu",
      "th": [
        "Menu"
      ],
      "banned": [],
      "surfaces": [
        "app"
      ],
      "fixed": true,
      "rule": "LR-01",
      "decided": "15/08/2026",
      "why": "Site navigation is English. See `our-services`.\n"
    },
    {
      "id": "nav-menu-close",
      "en": "Close menu",
      "th": [
        "Close menu"
      ],
      "banned": [],
      "surfaces": [
        "app"
      ],
      "fixed": true,
      "rule": "LR-01",
      "decided": "15/08/2026",
      "why": "Site navigation is English. See `our-services`.\n"
    },
    {
      "id": "nav-faq",
      "en": "FAQ",
      "th": [
        "FAQ"
      ],
      "banned": [],
      "surfaces": [
        "app"
      ],
      "fixed": true,
      "rule": "LR-01",
      "decided": "15/08/2026",
      "why": "Site navigation is English, and FAQ is already the form a Thai reader meets everywhere. See `our-services`.\n"
    },
    {
      "id": "nav-contact",
      "en": "Contact",
      "th": [
        "Contact"
      ],
      "banned": [],
      "surfaces": [
        "app"
      ],
      "fixed": true,
      "rule": "LR-01",
      "decided": "15/08/2026",
      "why": "Site navigation is English. See `our-services`.\n"
    },
    {
      "id": "nav-blog",
      "en": "Blog",
      "th": [
        "Blog"
      ],
      "banned": [],
      "surfaces": [
        "app"
      ],
      "fixed": true,
      "rule": "LR-01",
      "decided": "16/08/2026",
      "why": "English, decided 16/08/2026 (Paul), when the blog section was added and the menu item was drafted as บทความ. Site navigation is English and this entry is what makes that true of the sixth item rather than only of the five that were decided on 15/08/2026. Without it the passthrough check in `lint-thai.ts` correctly fails an English string sitting in the Thai column, because it cannot tell a decision from an untranslated key. See `our-services`.\n"
    },
    {
      "id": "our-services",
      "en": "Our Services",
      "th": [
        "Our Services"
      ],
      "banned": [],
      "surfaces": [
        "app"
      ],
      "fixed": true,
      "rule": "LR-01",
      "decided": "15/08/2026",
      "why": "English, decided 15/08/2026 (Paul), along with the rest of the site navigation: Menu, Close menu, Our Services, FAQ, Contact. ภาษา stays Thai because it labels a control rather than a destination.\nNavigation is chrome rather than voice. This audience reads English product navigation every day, and the Thai equivalents sit heavier in a menu than they do in prose, which is the register argument LR-05 already makes for loanwords. Nothing else moves to English on the strength of this: body copy, questions and the result screen stay Thai.\nWas บริการของเรา until 15/08/2026, on the reasoning that the possessive was doing work บริการ alone did not. That held for a Thai label and stops applying once the label is English.\n"
    },
    {
      "id": "contact-talk-to-me",
      "en": "Talk to me",
      "th": [
        "คุยกับผม"
      ],
      "banned": [
        "ติดต่อผม"
      ],
      "surfaces": [
        "app"
      ],
      "fixed": true,
      "rule": "LR-08",
      "decided": "14/08/2026",
      "why": "Paul's revision. ติดต่อ is what you do to a company, through a form. คุย is what two people do, and it is the promise the page makes: the next step is a conversation, not a ticket. First person because every service is delivered by him. ติดต่อเรา stays on the menu item deliberately, same reasoning inverted.\n"
    }
  ],
  "person": {
    "post": "เรา",
    "app": "เรา",
    "message": "ผม",
    "reader": "คุณ",
    "why": "เรา for the brand in broadcast copy, ผม in 1:1 messages where a brand plural reads evasive, คุณ for the reader always and stated rather than implied. The contact button คุยกับผม is first person on an app surface on purpose: it is the one string that opens a 1:1, so it speaks in the register of what it starts. Listed in `terms` above rather than treated as a person violation.\n"
  },
  "sourceHash": "d524677d037b6234"
} as const;

export const TERMS = TERMBASE.terms;
