/*
 * src/lib/design-tokens.generated.ts
 *
 * GENERATED by scripts/build-tokens.ts from design.md in the coaching repo.
 * Do not hand-edit. Edit the frontmatter there, run `npm run tokens`, commit
 * both. Source: getdesign wise template (npx getdesign add wise, v0.6.24, 25/08/2026); the Thai tiers, the dark scheme and the roles marked (PP) are PunProfile's and are derived and measured here
 * Design system version: wise-1
 */

/**
 * The brand token block for standalone HTML output: the candidate report, the
 * report book, the two-views demo. `src/app/tokens.generated.css` is the app's
 * copy; both come from the same source, so they cannot drift.
 *
 * **No dark block here, deliberately.** This string is for HTML generated
 * outside Next: a candidate's report, the report book, the two-views demo.
 * Those are documents a coach opens, prints and sends on, and a report that
 * renders dark because the reader's laptop is in dark mode is a report that
 * prints wrong and reads as broken when it lands in an inbox. Documents are
 * light.
 */
export const BRAND_TOKENS_CSS = `  :root {
    color-scheme: light;

    --viz-surface: #ffffff;
    --viz-page: #ecefeb;
    --viz-grid: #dfe3dc;
    --viz-muted: #6a6c6a;
    --viz-series-1: #38c8ff;
    --ink-1: #0e0f0c;
    --ink-2: #454745;
    --border: #dfe3dc;

    --color-primary: #9fe870;
    --color-on-primary: #163300;
    --color-primary-active: #cdffad;
    --color-primary-neutral: #c5edab;
    --color-primary-pale: #e2f6d5;
    --color-on-primary-pale: #163300;
    --color-ink: #0e0f0c;
    --color-ink-deep: #163300;
    --color-body: #454745;
    --color-mute: #868685;
    --color-mute-strong: #6a6c6a;
    --color-canvas: #ffffff;
    --color-canvas-soft: #ecefeb;
    --color-canvas-brand: #9fe870;
    --color-canvas-dark: #163300;
    --color-on-canvas-dark: #e8ebe6;
    --color-line: #dfe3dc;
    --color-line-strong: #8b908a;
    --color-positive: #2ead4b;
    --color-positive-deep: #054d28;
    --color-warning: #ffd11a;
    --color-warning-deep: #b86700;
    --color-warning-content: #4a3b1c;
    --color-negative: #d03238;
    --color-negative-deep: #a72027;
    --color-negative-darkest: #a7000d;
    --color-negative-bg: #320707;
    --color-accent-orange: #ffc091;
    --color-accent-cyan: #38c8ff;

    --color-primary-container: #e2f6d5;
    --color-on-primary-container: #163300;
    --color-secondary: #163300;
    --color-on-secondary: #cdffad;
    --color-secondary-container: #ecefeb;
    --color-on-secondary-container: #0e0f0c;
    --color-tertiary: #38c8ff;
    --color-on-tertiary: #163300;
    --color-tertiary-container: #e2f6d5;
    --color-on-tertiary-container: #163300;
    --color-action: #9fe870;
    --color-on-action: #163300;
    --color-action-container: #e2f6d5;
    --color-on-action-container: #163300;
    --color-on-warning: #4a3b1c;
    --color-warning-container: #ffd11a;
    --color-on-warning-container: #4a3b1c;
    --color-brand-orange: #ffc091;
    --color-on-brand-orange: #0e0f0c;
    --color-brand-lime: #9fe870;
    --color-on-brand-lime: #163300;
    --color-error: #d03238;
    --color-on-error: #ffffff;
    --color-error-container: #320707;
    --color-on-error-container: #ffffff;
    --color-background: #ffffff;
    --color-on-background: #163300;
    --color-surface: #ffffff;
    --color-on-surface: #163300;
    --color-surface-variant: #ecefeb;
    --color-on-surface-variant: #454745;
    --color-surface-dim: #ecefeb;
    --color-surface-bright: #ffffff;
    --color-surface-container-lowest: #ffffff;
    --color-surface-container-low: #ffffff;
    --color-surface-container: #ecefeb;
    --color-surface-container-high: #ecefeb;
    --color-surface-container-highest: #dfe3dc;
    --color-outline: #8b908a;
    --color-outline-variant: #dfe3dc;
    --color-inverse-surface: #163300;
    --color-inverse-on-surface: #e8ebe6;
    --color-primary-fixed: #e2f6d5;
    --color-primary-fixed-dim: #c5edab;
    --color-on-primary-fixed: #163300;
    --color-on-primary-fixed-variant: #163300;
    --color-secondary-fixed: #ecefeb;
    --color-secondary-fixed-dim: #dfe3dc;
    --color-on-secondary-fixed: #0e0f0c;
    --color-on-secondary-fixed-variant: #454745;
    --color-tertiary-fixed: #e2f6d5;
    --color-tertiary-fixed-dim: #c5edab;
    --color-on-tertiary-fixed: #163300;
    --color-on-tertiary-fixed-variant: #163300;
    --color-surface-tint: #9fe870;
    --color-shadow: #0e0f0c;
    --color-scrim: #163300;
    --color-inverse-primary: #9fe870;
  }`;

/**
 * Generated HTML cannot use `next/font`, so it links the families directly and
 * keeps a system fallback, which is what a report opened offline falls back to.
 */
export const BRAND_FONT_LINK = `<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700;800;900&family=Inter:wght@400;500;600;700;800;900&family=Anuphan:wght@400;500;600;700;800;900&display=swap">`;

export const BRAND_FONT_STACKS = `  --font-display: Archivo, Anuphan, system-ui, sans-serif;
  --font-sans: Inter, Anuphan, system-ui, -apple-system, "Segoe UI", sans-serif;`;
