/*
 * src/lib/design-tokens.generated.ts
 *
 * GENERATED by scripts/build-tokens.ts from design.md in the coaching repo.
 * Do not hand-edit. Edit the frontmatter there, run `npm run tokens`, commit
 * both. Source: ctxt-brand/pp_material_colors.json (Material Theme Builder export, 16/08/2026)
 * Design system version: m3-1
 */

/**
 * The brand token block for standalone HTML output: the candidate report, the
 * report book, the two-views demo. `src/app/tokens.generated.css` is the app's
 * copy; both come from the same source, so they cannot drift.
 *
 * **No dark block here, deliberately, and it is not the same reason as before.**
 * The app has a dark scheme since 16/08/2026. This string is for HTML generated
 * outside Next: a candidate's report, the report book, the two-views demo. Those
 * are documents a coach opens, prints and sends on, and a report that renders
 * dark because the reader's laptop is in dark mode is a report that prints
 * wrong and reads as broken when it lands in an inbox. Documents are light.
 */
export const BRAND_TOKENS_CSS = `  :root {
    color-scheme: light;

    --viz-surface: #ffffff;
    --viz-page: #f9faef;
    --viz-grid: #c6c8b8;
    --viz-muted: #45483c;
    --viz-series-1: #135cb4;
    --ink-1: #1a1d16;
    --ink-2: #45483c;
    --border: #c6c8b8;

    --color-primary: #566423;
    --color-on-primary: #ffffff;
    --color-primary-container: #d9eb9a;
    --color-on-primary-container: #3e4c0b;
    --color-secondary: #006a62;
    --color-tertiary: #135cb4;
    --color-on-tertiary: #ffffff;
    --color-tertiary-container: #d7e3ff;
    --color-action: #8f4c36;
    --color-on-action: #ffffff;
    --color-brand-orange: #e7703a;
    --color-surface: #f9faef;
    --color-on-surface: #1a1d16;
    --color-on-surface-variant: #45483c;
    --color-outline: #76786b;
    --color-outline-variant: #c6c8b8;
    --color-error: #904a43;
    --color-on-error: #ffffff;
  }`;

/**
 * Generated HTML cannot use `next/font`, so it links the families directly and
 * keeps a system fallback, which is what a report opened offline falls back to.
 */
export const BRAND_FONT_LINK = `<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:wght@400;500;600;700;800;900&family=Inter:wght@400;500;600;700;800;900&family=Anuphan:wght@400;500;600;700;800;900&display=swap">`;

export const BRAND_FONT_STACKS = `  --font-display: Fraunces, Anuphan, Georgia, serif;
  --font-sans: Inter, Anuphan, system-ui, -apple-system, "Segoe UI", sans-serif;`;
