/**
 * One file, every lead, with lifecycle state and fit grade already computed.
 * The feed for an agent that reads the lead dashboard's data without being the
 * dashboard.
 *
 *   npm run snapshot:leads              # exports both deployments, then builds
 *   npm run snapshot:leads -- --offline # rebuilds from the last raw export
 *
 * Writes `data/agent/leads-snapshot.json`. That directory is inside the app
 * repo's gitignored `data/` on purpose: this file holds real names, emails,
 * LINE IDs and phone numbers, and `data-inventory.md` is the record that it
 * exists. It must never be copied into the coaching repo, whose own gitignore
 * says in as many words that the method lives there and the people do not.
 *
 * **Nothing here decides anything.** State comes from `src/lib/lifecycle.ts`,
 * fit from `src/lib/leadGrade.ts`, scores from `convex/scoring.ts` and consent
 * from `src/lib/consent.ts`, imported and called. A rule reimplemented here
 * would be a second answer to a question that already has one, which is the
 * failure `leads.scores` and the stored `lifecycleStage` were both removed to
 * avoid. If a rule changes, re-run this; do not edit this file.
 *
 * **Both deployments, tagged.** `dashing-shepherd-41` is production and
 * `quiet-mule-251` is development, and dev is not a scratch environment: the 90
 * leads imported from the Lead Discovery Survey on 10/08/2026 are in it,
 * because production did not exist for another four days
 * (`data-inventory.md` § 1). A production-only snapshot silently drops them.
 *
 * **`personId` groups the same human across deployments.** It is a hash of the
 * lowercased email and nothing else, so it is stable between runs, reveals
 * nothing on its own, and gives an agent one key to group on instead of each
 * of them inventing a de-duplication rule. 92 people are currently in both
 * stores; counting rows without grouping overstates the pipeline.
 *
 * The header carries each deployment's row count and its most recent activity
 * date, which is the empirical answer to the standing Vercel question: if
 * `NEXT_PUBLIC_CONVEX_URL` is still scoped to Production, live traffic lands in
 * dev, and the giveaway is dev having fresher activity than prod. That case
 * emits a warning into the header rather than being left for someone to notice.
 *
 * **Temperature ships since 19/08/2026**, computed by `src/lib/temperature.ts`
 * from `08_Coaching_Business.md`'s recovered weights (TASK-055). Read it beside
 * Fit and never multiplied by it: that document keeps them independent axes on
 * purpose. Its own doc comment records what the port could not carry across,
 * and `temperature.unmeasured` repeats it per lead.
 */

import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";

import { scoresFor } from "../convex/scoring.js";
import { toScoringInputForLead } from "../src/lib/content/mapping.js";
import { temperatureFor, TEMPERATURE_TIERS } from "../src/lib/temperature.js";
import type { Temperature } from "../src/lib/temperature.js";
import { gradeLead, toGradeInput, latestCoachIcp } from "../src/lib/leadGrade.js";
import type { LeadGrade } from "../src/lib/leadGrade.js";
import {
  stateFor,
  meetsBookingGate,
  hasContact,
  LIFECYCLE_LABELS,
  LIFECYCLE_STATES,
} from "../src/lib/lifecycle.js";
import type { LifecycleState } from "../src/lib/lifecycle.js";
import { resolveConsent, ynGrid, CONSENT_PURPOSES } from "../src/lib/consent.js";
import type { ConsentChannel, ConsentEvent } from "../src/lib/consent.js";

const RAW_DIR = "data/agent/_raw";
const OUT = "data/agent/leads-snapshot.json";

/**
 * Deployment names are hardcoded because they are facts about this project, and
 * a name that has quietly changed should fail loudly here rather than produce a
 * correctly-shaped file about the wrong data. `--deployment prod` and `dev` are
 * the CLI's own selectors; the expected name is checked against what it reports.
 */
const SOURCES = [
  { ref: "prod", expectedName: "dashing-shepherd-41", role: "production" as const },
  { ref: "dev", expectedName: "quiet-mule-251", role: "development" as const },
];

// ------------------------------------------------------------- document types
//
// Only the fields this file reads. The full shapes are in `convex/schema.ts`,
// and restating them here would be a second schema to keep in step.

interface LeadDoc {
  _id: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  email?: string;
  phone?: string;
  lineId?: string;
  pathway?: string;
  responses?: Record<string, unknown>;
  status: "partial" | "email_captured" | "completed";
  source?: string;
  attribution?: { raw?: string };
  disposition?: string;
  dispositionReason?: string;
  linkedinUrl?: string;
  notes?: string;
  coachRating?: number;
  consentSource?: string;
  createdAt: number;
  lastActivityAt: number;
}

interface ConsultationDoc {
  leadId: string;
  outcome: string;
  heldAt: number;
  icpJobTitle?: string;
  icpExperienceYears?: string;
  icpPriorInvestment?: string;
}

interface EngagementDoc {
  leadId: string;
  status: string;
  agreedAt?: number;
}

interface PlacementDoc {
  leadId: string;
  signedAt?: number;
}

type ConsentEventDoc = ConsentEvent & { leadId: string };

// ------------------------------------------------------------------ utilities

/** House format. Epoch stays beside it, so nothing has to parse this back. */
function ddmmyyyy(ms: number | null): string | null {
  if (ms === null) return null;
  const d = new Date(ms);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${pad(d.getUTCDate())}/${pad(d.getUTCMonth() + 1)}/${d.getUTCFullYear()}`;
}

/**
 * One person, one id, however many rows they have.
 *
 * A hash rather than the address itself: the file already carries the email in
 * `contact`, so this buys no secrecy there, but it means anything that groups
 * or counts can pass around a key that is not personal data. Truncated to 16
 * hex characters, which at a few hundred people collides with probability far
 * below the odds of the sheet it replaced being wrong.
 */
function personIdFor(email: string | undefined): string | null {
  const normalised = email?.trim().toLowerCase();
  if (!normalised) return null;
  return createHash("sha256").update(normalised).digest("hex").slice(0, 16);
}

function readTable<T>(dir: string, table: string): T[] {
  const path = `${dir}/${table}/documents.jsonl`;
  if (!existsSync(path)) return [];
  return readFileSync(path, "utf8")
    .split("\n")
    .filter((line) => line.trim() !== "")
    .map((line) => JSON.parse(line) as T);
}

function groupByLead<T extends { leadId: string }>(rows: T[]): Map<string, T[]> {
  const out = new Map<string, T[]>();
  for (const row of rows) {
    const list = out.get(row.leadId) ?? [];
    list.push(row);
    out.set(row.leadId, list);
  }
  return out;
}

/**
 * Every channel they gave, withdrawn for every purpose. `lifecycle.ts` defines
 * `withdrawn` that way and the wording matters: a lead who never had consent
 * recorded on a channel is not someone who asked us to stop, so `never_asked`
 * does not count and the state stays whatever else they are.
 */
function fullyWithdrawn(lead: LeadDoc, events: ConsentEvent[]): boolean {
  const channels: ConsentChannel[] = [];
  if (lead.email) channels.push("email");
  if (lead.lineId) channels.push("line");
  if (lead.phone) channels.push("phone");
  if (channels.length === 0) return false;
  return channels.every((channel) =>
    CONSENT_PURPOSES.every(
      (purpose) => resolveConsent(events, channel, purpose).status === "opted_out",
    ),
  );
}

/**
 * "Agreed or beyond" read as "not still a proposal". `lapsed` and `refunded`
 * are what happened after a sale rather than instead of one, and a report that
 * demoted a refunded client back to a lead would be claiming they never bought.
 */
const AGREED_OR_BEYOND = new Set(["agreed", "active", "completed", "lapsed", "refunded"]);

/**
 * Same predicate the dashboard list uses, restated only because that one is a
 * Convex helper and this runs offline. Someone who handed over an email on the
 * blog has not started the check; they stay in the file with a flag so a
 * consumer can count them or exclude them, which the dashboard cannot do.
 */
const BLOG_SIGNUP = "blog_signup";
const isBlogOnly = (lead: LeadDoc) =>
  lead.attribution?.raw === BLOG_SIGNUP && Object.keys(lead.responses ?? {}).length === 0;

// ------------------------------------------------------------------- the pull

const offline = process.argv.includes("--offline");

interface SourceMeta {
  ref: string;
  role: string;
  expectedName: string;
  reportedName: string | null;
  rows: number;
  latestActivityAt: number | null;
  latestActivityDate: string | null;
}

const warnings: string[] = [];

function pull(ref: string, expectedName: string): { dir: string; reportedName: string | null } {
  const dir = `${RAW_DIR}/${ref}`;
  const zip = `${RAW_DIR}/${ref}.zip`;

  if (offline) {
    if (!existsSync(dir)) {
      throw new Error(`--offline but no previous export at ${dir}. Run without --offline once.`);
    }
    return { dir, reportedName: null };
  }

  mkdirSync(RAW_DIR, { recursive: true });
  rmSync(zip, { force: true });
  rmSync(dir, { recursive: true, force: true });

  // stderr is where the CLI narrates; it names the deployment it connected to,
  // which is the only chance to catch a snapshot of the wrong one.
  const out = execFileSync(
    "npx",
    ["convex", "export", "--deployment", ref, "--path", zip],
    { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
  );
  const chatter = String(out);
  const match = chatter.match(/[a-z]+-[a-z]+-\d+/);
  const reportedName = match ? match[0] : null;
  if (reportedName && reportedName !== expectedName) {
    warnings.push(
      `${ref}: expected deployment ${expectedName}, the CLI named ${reportedName}. ` +
        `Either the project moved or this script is out of date.`,
    );
  }

  execFileSync("unzip", ["-o", "-q", zip, "-d", dir], { stdio: "inherit" });
  return { dir, reportedName };
}

// ------------------------------------------------------------------ the build

interface Row {
  deployment: string;
  deploymentRole: string;
  leadId: string;
  /** Stable across deployments and runs. Null when no email was captured. */
  personId: string | null;
  createdAt: number;
  createdDate: string | null;
  lastActivityAt: number;
  lastActivityDate: string | null;
  status: string;
  disposition: string | null;
  dispositionReason: string | null;
  source: string | null;
  attributionRaw: string | null;
  blogOnlySubscriber: boolean;
  answered: number;
  pathway: string | null;
  contact: {
    firstName: string | null;
    lastName: string | null;
    fullName: string | null;
    email: string | null;
    phone: string | null;
    lineId: string | null;
    consentSource: string | null;
  };
  consent: Record<string, string>;
  lifecycle: {
    state: LifecycleState;
    label: string;
    inputs: {
      hasContact: boolean;
      meetsSqlRule: boolean;
      consultationsHeld: number;
      engagementsAgreed: number;
      placementsSigned: number;
      fullyWithdrawn: boolean;
    };
  };
  fit: LeadGrade;
  temperature: Temperature;
  scores: Record<string, number>;
  coach: {
    rating: number | null;
    linkedinUrl: string | null;
    hasNotes: boolean;
    lastConsultationAt: number | null;
    consultationsTotal: number;
  };
}

const rows: Row[] = [];
const sources: SourceMeta[] = [];

for (const source of SOURCES) {
  const { dir, reportedName } = pull(source.ref, source.expectedName);

  const leads = readTable<LeadDoc>(dir, "leads");
  const consultations = groupByLead(readTable<ConsultationDoc>(dir, "consultations"));
  const engagements = groupByLead(readTable<EngagementDoc>(dir, "engagements"));
  const placements = groupByLead(readTable<PlacementDoc>(dir, "placements"));
  const consents = groupByLead(readTable<ConsentEventDoc>(dir, "consentEvents"));

  for (const lead of leads) {
    const calls = consultations.get(lead._id) ?? [];
    const held = calls.filter((c) => c.outcome === "held");
    const events = consents.get(lead._id) ?? [];
    const inputs = {
      hasContact: hasContact(lead),
      meetsSqlRule: meetsBookingGate(lead.responses),
      consultationsHeld: held.length,
      engagementsAgreed: (engagements.get(lead._id) ?? []).filter((e) =>
        AGREED_OR_BEYOND.has(e.status),
      ).length,
      placementsSigned: (placements.get(lead._id) ?? []).filter(
        (p) => typeof p.signedAt === "number",
      ).length,
      fullyWithdrawn: fullyWithdrawn(lead, events),
    };

    rows.push({
      deployment: source.expectedName,
      deploymentRole: source.role,
      leadId: lead._id,
      personId: personIdFor(lead.email),
      createdAt: lead.createdAt,
      createdDate: ddmmyyyy(lead.createdAt),
      lastActivityAt: lead.lastActivityAt,
      lastActivityDate: ddmmyyyy(lead.lastActivityAt),
      status: lead.status,
      disposition: lead.disposition ?? null,
      dispositionReason: lead.dispositionReason ?? null,
      source: lead.source ?? null,
      attributionRaw: lead.attribution?.raw ?? null,
      blogOnlySubscriber: isBlogOnly(lead),
      answered: Object.keys(lead.responses ?? {}).length,
      pathway: lead.pathway ?? null,
      contact: {
        firstName: lead.firstName ?? null,
        lastName: lead.lastName ?? null,
        fullName: lead.fullName ?? null,
        email: lead.email ?? null,
        phone: lead.phone ?? null,
        lineId: lead.lineId ?? null,
        consentSource: lead.consentSource ?? null,
      },
      consent: ynGrid(events),
      lifecycle: {
        state: stateFor(inputs),
        label: LIFECYCLE_LABELS[stateFor(inputs)],
        inputs,
      },
      fit: gradeLead(toGradeInput(lead.responses ?? {}), latestCoachIcp(calls)),
      // `toScoringInputForLead`, so the 90 imported leads are read in the survey
      // vocabulary rather than the app's. Same mapper the scores use; a second
      // reader here would be a second answer to "what did they say".
      temperature: temperatureFor(toScoringInputForLead(lead.responses ?? {})),
      scores: scoresFor(lead.responses) as Record<string, number>,
      coach: {
        rating: lead.coachRating ?? null,
        linkedinUrl: lead.linkedinUrl ?? null,
        hasNotes: Boolean(lead.notes),
        lastConsultationAt: held.length
          ? held.reduce((max, c) => (c.heldAt > max ? c.heldAt : max), 0)
          : null,
        consultationsTotal: calls.length,
      },
    });
  }

  const latest = leads.reduce<number | null>(
    (max, l) => (max === null || l.lastActivityAt > max ? l.lastActivityAt : max),
    null,
  );
  sources.push({
    ref: source.ref,
    role: source.role,
    expectedName: source.expectedName,
    reportedName,
    rows: leads.length,
    latestActivityAt: latest,
    latestActivityDate: ddmmyyyy(latest),
  });
}

// The Vercel check, stated as a fact about the data rather than a config read.
// Dev holds the 10/08/2026 import and nothing since, so dev being the fresher
// deployment means live traffic is writing there.
const prod = sources.find((s) => s.role === "production");
const dev = sources.find((s) => s.role === "development");
if (prod && dev && prod.latestActivityAt !== null && dev.latestActivityAt !== null) {
  if (dev.latestActivityAt > prod.latestActivityAt) {
    warnings.push(
      `Development ${dev.expectedName} has fresher activity (${dev.latestActivityDate}) than ` +
        `production ${prod.expectedName} (${prod.latestActivityDate}). Check whether Vercel's ` +
        `NEXT_PUBLIC_CONVEX_URL is still scoped to Production; live traffic may be writing to dev.`,
    );
  }
}

// One person, two deployments. Not merged: which store a row is in is a fact
// the reader needs, and silently collapsing two rows would hide it.
const byEmail = new Map<string, string[]>();
for (const row of rows) {
  const email = row.contact.email?.trim().toLowerCase();
  if (!email) continue;
  const list = byEmail.get(email) ?? [];
  list.push(row.deployment);
  byEmail.set(email, list);
}
const crossDeployment = [...byEmail.entries()].filter(
  ([, deployments]) => new Set(deployments).size > 1,
).length;
if (crossDeployment > 0) {
  warnings.push(
    `${crossDeployment} email address(es) appear in both deployments. Rows are kept separate and ` +
      `tagged; de-duplicate on email before counting people.`,
  );
}

const count = <T extends string>(keys: readonly T[], pick: (r: Row) => T | null) => {
  const out: Record<string, number> = {};
  for (const k of keys) out[k] = 0;
  for (const r of rows) {
    const k = pick(r);
    if (k === null) continue;
    out[k] = (out[k] ?? 0) + 1;
  }
  return out;
};

const now = Date.now();
const snapshot = {
  meta: {
    generatedAt: new Date(now).toISOString(),
    generatedDate: ddmmyyyy(now),
    generator: "scripts/export-leads-snapshot.ts",
    contains: "personal data: names, email addresses, phone numbers, LINE IDs",
    sources,
    totals: {
      rows: rows.length,
      byLifecycleState: count(LIFECYCLE_STATES, (r) => r.lifecycle.state),
      byFitTier: count(["weak", "moderate", "strong"] as const, (r) => r.fit.tier),
      byTemperatureTier: {
        ...count(TEMPERATURE_TIERS, (r) => r.temperature.tier),
        // Not a tier. The band could not be pinned down because answers are
        // missing, which is a different statement from "cold".
        undetermined: rows.filter((r) => r.temperature.tier === null).length,
      },
      people: new Set(rows.map((r) => r.personId).filter(Boolean)).size,
      byStatus: count(["partial", "email_captured", "completed"] as const, (r) => r.status as never),
      blogOnlySubscribers: rows.filter((r) => r.blogOnlySubscriber).length,
    },
    rules: {
      lifecycleState: "src/lib/lifecycle.ts stateFor()",
      sqlGate: "src/lib/lifecycle.ts meetsBookingGate() — the wave 1 booking rule, 14/08/2026",
      fit: "src/lib/leadGrade.ts gradeLead() — two gates and Investment Readiness 0-3",
      scores: "convex/scoring.ts scoresFor() — recomputed from responses, never read from storage",
      consent: "src/lib/consent.ts ynGrid() — Y, N, or empty for never asked",
      temperature:
        "src/lib/temperature.ts temperatureFor() - the weights recovered into 08_Coaching_Business.md " +
        "on 14/08/2026, ported 19/08/2026 (TASK-055). Independent of Fit by design, never combined. " +
        "Q4 response rate is not asked anywhere, so that input caps at 1 of 2 and the reachable " +
        "maximum is 9; tier is null when missing answers leave the band genuinely undetermined.",
      personId: "sha256 of the lowercased email, first 16 hex. Group on it before counting people.",
    },
    warnings,
  },
  rows,
};

mkdirSync("data/agent", { recursive: true });
writeFileSync(OUT, JSON.stringify(snapshot, null, 2) + "\n");

console.log(`${OUT}: ${rows.length} rows, ${snapshot.meta.totals.people} distinct people`);
for (const s of sources) {
  console.log(`  ${s.role.padEnd(11)} ${s.expectedName}  ${s.rows} rows, latest ${s.latestActivityDate ?? "none"}`);
}
for (const w of warnings) console.log(`  warning: ${w}`);
