/**
 * Copies the termbase out of the coaching repo and into this one.
 *
 *   npx tsx scripts/sync-termbase.ts
 *
 * `termbase.yml` in `../punprofile-career-coaching/punprofile-context/ctxt-content/`
 * is the source and the only place it is edited. This script emits
 * `src/lib/content/termbase.generated.ts`, which the lint and the drafting
 * protocol read.
 *
 * Why a copy rather than a cross-repo import: this repo holds implementation and
 * must build on its own. The same reason `daily-jobs` reads a generated
 * `run-brief.md` instead of six context documents.
 *
 * The generated file is never hand-edited. Edit the YAML, re-run this, commit
 * both. `verify-copy.ts` fails if the two have drifted.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { load } from "js-yaml";

const SOURCE =
  "../punprofile-career-coaching/punprofile-context/ctxt-content/termbase.yml";
const OUT = "src/lib/content/termbase.generated.ts";

/**
 * `value` is the odd one out: not something a candidate reads, but something
 * they type or pick, which LR-02 says is supplied in English. It never appears
 * in a termbase entry's `surfaces`, only on a lint target.
 */
export type Surface =
  | "post"
  | "app"
  | "survey"
  | "message"
  | "system"
  | "value"
  | "all";

export interface Term {
  id: string;
  en: string;
  th: string[];
  banned: string[];
  surfaces: Surface[];
  fixed: boolean;
  rule: string;
  decided: string;
  why: string;
  /** Present only where the decision is recorded but the code disagrees. */
  conflict?: string;
}

export interface Termbase {
  version: number;
  updated: string;
  terms: Term[];
  person: Record<string, string>;
  /** sha256 of the source YAML, so drift is detectable without re-reading it. */
  sourceHash: string;
}

/** Parses the YAML and fails loudly on anything the lint would silently skip. */
export function parseTermbase(yaml: string): Omit<Termbase, "sourceHash"> {
  const raw = load(yaml) as Record<string, unknown>;
  const terms = raw.terms as Term[];

  if (!Array.isArray(terms) || terms.length === 0) {
    throw new Error("termbase.yml has no terms");
  }

  const seen = new Set<string>();
  for (const t of terms) {
    for (const field of ["id", "en", "rule", "decided", "why"] as const) {
      if (!t[field]) throw new Error(`term ${t.id ?? "?"}: missing ${field}`);
    }
    if (seen.has(t.id)) throw new Error(`term ${t.id}: duplicate id`);
    seen.add(t.id);

    // A term with no accepted rendering cannot be checked against anything, and
    // a `fixed` term with several is not fixed.
    if (!Array.isArray(t.th) || t.th.length === 0) {
      throw new Error(`term ${t.id}: no accepted Thai rendering`);
    }
    if (t.fixed && t.th.length !== 1) {
      throw new Error(`term ${t.id}: fixed, so it needs exactly one rendering`);
    }
    // The list the lint scans has to stay disjoint from the list it accepts, or
    // a term fails on its own approved form.
    for (const b of t.banned ?? []) {
      if (t.th.some((ok) => ok.includes(b))) {
        throw new Error(`term ${t.id}: banned form "${b}" occurs inside an accepted one`);
      }
    }
    if (!/^\d{2}\/\d{2}\/\d{4}$/.test(t.decided)) {
      throw new Error(`term ${t.id}: decided "${t.decided}" is not DD/MM/YYYY`);
    }
  }

  return {
    version: raw.version as number,
    updated: raw.updated as string,
    terms: terms.map((t) => ({ ...t, banned: t.banned ?? [] })),
    person: (raw.person ?? {}) as Record<string, string>,
  };
}

export function hashOf(yaml: string): string {
  return createHash("sha256").update(yaml).digest("hex").slice(0, 16);
}

export function readSource(): { yaml: string; missing: boolean } {
  if (!existsSync(SOURCE)) return { yaml: "", missing: true };
  return { yaml: readFileSync(SOURCE, "utf8"), missing: false };
}

function main() {
  const { yaml, missing } = readSource();
  if (missing) {
    console.error(`FAIL cannot read ${SOURCE}`);
    console.error("The coaching repo must sit beside this one for a sync to run.");
    process.exit(1);
  }

  const parsed = parseTermbase(yaml);
  const base: Termbase = { ...parsed, sourceHash: hashOf(yaml) };

  const body = `/**
 * GENERATED by scripts/sync-termbase.ts. Do not edit.
 *
 * Source: ${SOURCE}
 * Source updated: ${base.updated}
 *
 * Edit the YAML in the coaching repo, re-run the sync, commit both files.
 */

import type { Termbase } from "../../../scripts/sync-termbase";

export const TERMBASE: Termbase = ${JSON.stringify(base, null, 2)} as const;

export const TERMS = TERMBASE.terms;
`;

  writeFileSync(OUT, body);
  const conflicts = base.terms.filter((t) => t.conflict);
  console.log(
    `termbase synced: ${base.terms.length} terms, ` +
      `${base.terms.filter((t) => t.fixed).length} fixed, hash ${base.sourceHash}`,
  );
  if (conflicts.length) {
    console.log(`\n${conflicts.length} term(s) carry an unresolved conflict:`);
    for (const c of conflicts) console.log(`  ${c.id}`);
  }
}

if (process.argv[1]?.endsWith("sync-termbase.ts")) main();
