/**
 * Copies the job pipeline's headline figures out of the coaching repo.
 *
 *   npx tsx scripts/sync-market-snapshot.ts
 *
 * `job-log.json` in `../punprofile-career-coaching/punprofile-work/work-pipeline/`
 * is the source. It is rewritten every evening by the `daily-jobs` automation,
 * which is exactly why this is a snapshot and not a read: the app cannot reach
 * across repos at runtime, and it should not, because a candidate-facing figure
 * that changes under the reader is worse than one that is a week old and says
 * so. Same reason as `sync-termbase.ts`.
 *
 * **The snapshot carries a date and the screen prints it.** A stale figure that
 * names its own date is honest. A stale figure that does not is the trust
 * failure this whole product is trying to avoid.
 *
 * **What is deliberately not emitted: the country split.** Of the 84 published
 * roles in the 16/08/2026 snapshot, 64 are in Germany, and that is a fact about
 * the board the pipeline sources from, not about Europe. Publishing it would be
 * the mistake the workspace `CLAUDE.md` warns about, one layer down: reading the
 * shape of the market off an artefact of how we collect it. If the sourcing ever
 * widens, this is the note to revisit.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";

const SOURCE = "../punprofile-career-coaching/punprofile-work/work-pipeline/job-log.json";
const OUT = "src/lib/content/market-snapshot.generated.ts";

interface JobRow {
  employer: string;
  country: string;
  first_seen: string;
  verdict: string;
}

export interface MarketSnapshot {
  /** Every role the pipeline evaluated in the window, whatever the verdict. */
  screened: number;
  /** Verdict `publish`: cleared the sponsorship and credibility bar. */
  published: number;
  /** Distinct employers behind the published set. */
  employers: number;
  /** DD/MM/YYYY, the earliest and latest `first_seen` in the log. */
  from: string;
  to: string;
}

/** `2026-07-07` to `07/07/2026`, the house date format. */
function toHouseDate(iso: string): string {
  const [y, m, d] = iso.split("-");
  return `${d}/${m}/${y}`;
}

export function summarise(rows: JobRow[]): MarketSnapshot {
  if (!rows.length) throw new Error("job-log.json is empty");

  const published = rows.filter((r) => r.verdict === "publish");
  // A screened row with no date would silently widen or narrow the window,
  // which is the one number a reader can check against the Facebook group.
  const dates = rows.map((r) => r.first_seen).filter(Boolean).sort();
  if (dates.length !== rows.length) throw new Error("job-log.json has rows with no first_seen");

  return {
    screened: rows.length,
    published: published.length,
    employers: new Set(published.map((r) => r.employer)).size,
    from: toHouseDate(dates[0]),
    to: toHouseDate(dates[dates.length - 1]),
  };
}

function main() {
  if (!existsSync(SOURCE)) {
    console.error(`FAIL cannot read ${SOURCE}`);
    console.error("The coaching repo must sit beside this one for a sync to run.");
    process.exit(1);
  }

  const rows = JSON.parse(readFileSync(SOURCE, "utf8")) as JobRow[];
  const snap = summarise(rows);

  const body = `/**
 * GENERATED by scripts/sync-market-snapshot.ts. Do not edit.
 *
 * Source: ${SOURCE}
 *
 * Re-run the sync and commit both files when the figures should move. Nothing
 * updates this automatically, on purpose: a candidate-facing number changes
 * when someone decides it should.
 */

import type { MarketSnapshot } from "../../../scripts/sync-market-snapshot";

export const MARKET: MarketSnapshot = ${JSON.stringify(snap, null, 2)} as const;
`;

  writeFileSync(OUT, body);
  console.log(
    `market snapshot: ${snap.screened} screened, ${snap.published} published, ` +
      `${snap.employers} employers, ${snap.from} to ${snap.to}`,
  );
}

if (process.argv[1]?.endsWith("sync-market-snapshot.ts")) main();
